### PR TITLE
feat: add CI for deterministic build using srtool #75

### PR DESCRIPTION
**Pull request by peterwht**
Solves https://github.com/paritytech/extended-parachain-template/issues/75

### CODE REVIEW

**Comment by evilrobot-01** [comment]
Nice! Is there a sample output of the subwasm results? Could we maybe generate a draft release off this branch to trigger the workflow to see the results?

**Comment by peterwht** [comment]
@evilrobot-01 Absolutely! Here is some test output on fork:
- https://github.com/peterwht/extended-parachain-template/releases/tag/test-v8
- https://github.com/peterwht/extended-parachain-template/actions/runs/6305423211/job/17118818501

**Comment by evilrobot-01** [comment]
Excellent! I see the subwasm info artifacts are attached to the action run and not the release. Just checking whether this is intentional?

**Comment by peterwht** [comment]
@evilrobot-01 Good catch! I will add those in as well

**Comment by peterwht** [comment]
@evilrobot-01 fixed in latest commit. See:
- https://github.com/peterwht/extended-parachain-template/actions/runs/6328750202
- https://github.com/peterwht/extended-parachain-template/releases/tag/test-v9-tag

**Review by stiiifff — APPROVED** [review]

**Pull request merged**
